# Generated by Django 5.1.7 on 2025-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address_first_line', models.CharField(max_length=200)),
                ('address_second_line', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=7)),
            ],
        ),
    ]
